// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh0xTDPfGEXRTQx_XUT4sNJmib5cxsm80',
    appId: '1:803125168649:web:a646d5b1ecd8d8c528c6d8',
    messagingSenderId: '803125168649',
    projectId: 'eduguide-71af2',
    authDomain: 'eduguide-71af2.firebaseapp.com',
    databaseURL: 'https://eduguide-71af2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eduguide-71af2.firebasestorage.app',
    measurementId: 'G-JX0HL751FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgmXZs6PnAom0-CixMT6PC7pFFNoDcQ_g',
    appId: '1:803125168649:android:4ac33294d194b53c28c6d8',
    messagingSenderId: '803125168649',
    projectId: 'eduguide-71af2',
    databaseURL: 'https://eduguide-71af2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eduguide-71af2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4F4IELvIPJOMbqWt-0CEsCHGrnDVPLrs',
    appId: '1:803125168649:ios:afede4248261612c28c6d8',
    messagingSenderId: '803125168649',
    projectId: 'eduguide-71af2',
    databaseURL: 'https://eduguide-71af2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eduguide-71af2.firebasestorage.app',
    iosBundleId: 'com.example.eduGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4F4IELvIPJOMbqWt-0CEsCHGrnDVPLrs',
    appId: '1:803125168649:ios:afede4248261612c28c6d8',
    messagingSenderId: '803125168649',
    projectId: 'eduguide-71af2',
    databaseURL: 'https://eduguide-71af2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eduguide-71af2.firebasestorage.app',
    iosBundleId: 'com.example.eduGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh0xTDPfGEXRTQx_XUT4sNJmib5cxsm80',
    appId: '1:803125168649:web:4d42bf43eefbc69a28c6d8',
    messagingSenderId: '803125168649',
    projectId: 'eduguide-71af2',
    authDomain: 'eduguide-71af2.firebaseapp.com',
    databaseURL: 'https://eduguide-71af2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eduguide-71af2.firebasestorage.app',
    measurementId: 'G-BW46DLT4CQ',
  );
}
